add pagination
Agreon/budgie pull request #105
Opened 2021-03-04 18:43 UTC by bexrr

closes #68

2021-03-06 08:51 UTC, Agreon approved these changes
Wow :D

2021-03-13 07:02 UTC, Agreon requested changes

2021-03-13 07:02 UTC, Agreon commented on server/income.go
> +	page = strconv.Itoa(pageInt * pageSize)
Could you extract that into a method/middleware?

2021-03-13 08:26 UTC, bexrr commented on budgie-app/src/screens/expenses/CreateExpense.tsx
> +        const { data: tags } = await api.get('tag?page=0');
What's that supposed to be?????? :rage:

2021-03-13 08:33 UTC, bexrr commented on budgie-app/src/screens/expenses/EditExpense.tsx
> +        const { data: tags } = await api.get('tag?page=0');
Same as above..

2021-03-13 08:41 UTC, merged