add recurring filter
Agreon/budgie pull request #181
Opened 2021-05-15 07:51 UTC by bexrr

closes #179

2021-06-11 13:36 UTC, bexrr commented
@Agreon please review

2021-07-01 07:37 UTC, Agreon requested changes
Good work, almost :hankey:

2021-07-01 07:37 UTC, Agreon commented on server/recurring.go
> +	startDate, existingStartDate := filterOptions["start_date>"]
```suggestion
	endDate, endDateExists := filterOptions["end_date<"]
	startDate, startDateExists := filterOptions["start_date>"]
```

2021-07-01 07:37 UTC, Agreon commented on server/recurring.go
> +					id,	name, costs, user_id, category, is_expense,
```suggestion
					id, name, costs, user_id, category, is_expense, 
```

2021-07-01 07:37 UTC, Agreon commented on server/recurring.go
> +			) AS relevant_recurring
```suggestion
			SELECT count(*)  
				FROM recurring
				WHERE
					user_id=$1 AND is_expense=$2 AND start_date<$3 AND (end_date>$4 OR end_date=$5)
			
```

2021-07-01 07:56 UTC, Agreon approved these changes

2021-07-01 07:56 UTC, merged